"""add due_date, priority, work_type fields to tasks table

Revision ID: 4a58aaf0eeb4
Revises: 
Create Date: 2026-02-02 02:57:10.795774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel

# revision identifiers, used by Alembic.
revision: str = '4a58aaf0eeb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium'))
    op.add_column('tasks', sa.Column('work_type', sa.String(length=20), nullable=False, server_default='personal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'work_type')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
